# Generated by Django 3.2.25 on 2025-07-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
