# Generated by Django 3.2.25 on 2025-07-04 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fly', '0002_tourpackage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
