# Generated by Django 3.2.25 on 2025-07-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0006_auto_20250717_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor')], default='user', max_length=10),
        ),
    ]
