# Generated by Django 3.2.25 on 2025-07-20 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0008_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='created_by',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
